// Canonical content for the site.

window.SITE_DATA = {
  identity: {
    name: "Rishika Mohanta",
    pronunciation: "Ree-shee-ka Moh-hun-tah",
    pronouns: "she/her",
    tagline: "Insect neuroscience · tools for discovery",
    pitch: "Theorist at heart, tool-builder by skill, experimentalist by ambition, comparative neuroethologist by philosophy. I study how sensory anatomy shapes neural computation across species — and I build the rigs and software that make that question answerable.",
    location: "The Rockefeller University · New York",
    orcid: "0000-0002-1396-3215",
    emails: { work: "rmohanta [at] rockefeller.edu", personal: "neurorishika [at] gmail.com" },
    social: [
      { k: "github",    label: "GitHub",      href: "https://github.com/neurorishika/" },
      { k: "scholar",   label: "Scholar",     href: "https://scholar.google.com/citations?user=xe4WM_UAAAAJ" },
      { k: "orcid",     label: "ORCID",       href: "https://orcid.org/0000-0002-1396-3215" },
      { k: "linkedin",  label: "LinkedIn",    href: "https://www.linkedin.com/in/neurorishika/" },
      { k: "twitter",   label: "Twitter",     href: "https://twitter.com/NeuroRishika" },
      { k: "youtube",   label: "YouTube",     href: "https://www.youtube.com/@neurorishika" },
    ],
  },

  now: {
    updated: "April 2026",
    items: [
      "Joint PhD with Vanessa Ruta & Daniel Kronauer — running bilateral navigation experiments in clonal raider ants and Drosophila with FlyCLOPS and MultiBiOS.",
      "Ant reference brain just published in Current Biology (Frank, Lopes, Mohanta et al. 2026) — community atlas for ant neuroscience is live.",
      "Shipping HYDRA Suite v1.0 — multi-animal tracking with GPU acceleration and interactive proofreading.",
      "Running a Pathfinder 2e campaign on weekends; slowly working through Hölldobler & Wilson.",
    ],
  },

  pillars: [
    {
      id: "navigation",
      title: "Bilateral navigation & olfactory circuits",
      lede: "How do bilateral sensory comparisons underlie pheromone trail-following — and how does that computation differ when ants smell with 120,000 olfactory neurons and flies with 1,200?",
      threads: [
        { y: "2023–", t: "Bilateral olfactory navigation in O. biroi and Drosophila — using FlyCLOPS and MultiBiOS to compare algorithms across species with 100× difference in olfactory scale (Ruta + Kronauer labs)." },
        { y: "2026",   t: "First neuroanatomical reference brain for the clonal raider ant — published in Current Biology; now a shared community resource." },
        { y: "2019–21", t: "Locust antennal-lobe dynamics under fluctuating and overlapping odor inputs (Assisi Lab)." },
      ],
    },
    {
      id: "learning",
      title: "Value, memory & decision-making",
      lede: "Flies, ants, and mice all learn from reward and punishment, but the circuits look wildly different. I use behavior + imaging + models to ask what computational rules they share.",
      threads: [
        { y: "2022–23", t: "Choice engineering in fruit flies — model-driven manipulation of olfactory decisions (Turner Lab + DeepMind)." },
        { y: "2023",    t: "Enumerating maximally discriminative tasks to probe foraging strategies (Hermundstad Lab · CCN 2023, Cosyne 2024)." },
        { y: "2019",    t: "Olfactory learning in closed-loop fly-on-ball VR (Turner Lab · Janelia)." },
      ],
    },
    {
      id: "tools",
      title: "Tools for neuroethology",
      lede: "Comparative work needs comparable data — shared rigs, shared pipelines, shared reference frames. Most of my tools exist because I needed them for my own science, and kept getting useful to others.",
      threads: [
        { y: "2025–", t: "HYDRA Suite — multi-animal tracking, pose labeling, and interactive proofreading in one toolkit." },
        { y: "2023–", t: "FlyCLOPS · FlyProjection · MultiBiOS — closed-loop optogenetic trail system, visual arena, and bilateral olfactometer for comparative neuroethology." },
        { y: "2019",  t: "Parallel TensorFlow framework for biological neural-network simulation (published in NBDT)." },
      ],
    },
  ],

  tools: [
    {
      name: "HYDRA Suite",
      tag: "tracking",
      status: "beta · active",
      year: "2025",
      lang: "Python",
      blurb: "Holistic YOLO-based Detection, Recognition, and Analysis — multi-animal tracking, pose labeling, classification, and interactive proofreading in one toolkit.",
      href: "https://github.com/neurorishika/hydra-suite",
      preview: "tracking",
    },
    {
      name: "ArthroScape",
      tag: "simulation",
      status: "research",
      year: "2024",
      lang: "Python",
      blurb: "Arthropod behavioral simulation toolkit — modeling chemosensory navigation, trail formation, and collective behavior from individual neural rules.",
      href: "https://github.com/neurorishika/ArthroScape",
      preview: "map",
    },
    {
      name: "FlyManager",
      tag: "lab ops",
      status: "stable",
      year: "2023",
      lang: "Python",
      blurb: "Drosophila stock-keeping for research labs — genotype tracking, crossing schedules, vial aging. Quiet, reliable, boring.",
      href: "https://github.com/neurorishika/FlyManager",
      preview: "stock",
    },
    {
      name: "MiniVentory",
      tag: "lab ops",
      status: "stable",
      year: "2023",
      lang: "Python",
      blurb: "Minimal lab inventory tracker — consumables checkout, low-stock email alerts, and automated replenishment. No login required.",
      href: "https://github.com/neurorishika/MiniVentory",
      preview: "inventory",
    },
  ],

  rigs: [
    { name: "Fly-on-ball olfactory VR", year: "2019 · Turner Lab · Janelia", desc: "Closed-loop walking arena with calibrated odor delivery, used to probe how olfactory learning shapes exploratory behavior in Drosophila." },
    { name: "FlyCLOPS optogenetic trail system", year: "2023 · Ruta Lab · Rockefeller", desc: "Closed-loop optogenetic system for virtual pheromone trail following. Light activation of specific olfactory receptor neurons generates bilateral odor gradients in freely-walking flies — no chemistry required." },
    { name: "FlyProjection closed-loop arena", year: "2024 · Ruta Lab · Rockefeller", desc: "Top-down projector + high-speed IR camera. Real-time GPU-accelerated tracking drives arbitrary 2D visual worlds rendered beneath freely-walking flies." },
    { name: "MultiBiOS bilateral olfactometer", year: "2024 · Ruta + Kronauer Labs · Rockefeller", desc: "Hardware-clocked bilateral odor delivery (NI-DAQ + Teensy 4.1) for comparative pheromone trail-following experiments in both ants and flies." },
  ],

  publications: [
    {
      n: 1,
      authors: "Frank, D.D., Lopes, L.E., Mohanta, R., Seckler, I., Lacroix, I., Kronauer, D.J.C.",
      title: "A reference brain for the clonal raider ant",
      venue: "Current Biology 36(1):227–235.e3",
      year: "2026",
      href: "https://doi.org/10.1016/j.cub.2025.11.018",
    },
    {
      n: 2,
      authors: "Castro, P.S.*, Tomasev, N.*, Anand, A., Sharma, N., Mohanta, R., Dev, A., et al.",
      title: "Discovering Symbolic Cognitive Models from Human and Animal Behavior",
      venue: "ICML 2025",
      year: "2025",
      href: null,
    },
    {
      n: 3,
      authors: "Grima, L.L., Haberkern, H., Mohanta, R., Morimoto, M.M., Rajagopalan, A.E., Scholey, E.V., et al.",
      title: "Foraging as an ethological framework for neuroscience",
      venue: "Trends in Neurosciences 48:877–890",
      year: "2025",
      href: null,
    },
    {
      n: 4,
      authors: "Ma, T.*, Mohanta, R.*, Dev, A., Turner, G.C., Hermundstad, A.M.",
      title: "Enumerating and Discovering Highly Discriminative Tasks for Probing Diverse Foraging Strategies",
      venue: "CCN 2023",
      year: "2023",
      href: "https://doi.org/10.32470/CCN.2023.1217-0",
    },
    {
      n: 5,
      authors: "Mohanta, R. & Assisi, C.",
      title: "Parallel scalable simulations of biological neural networks using TensorFlow: a beginner's guide",
      venue: "Neurons, Behavior, Data Analysis and Theory",
      year: "2022",
      href: "https://doi.org/10.51628/001c.37893",
    },
    {
      n: 6,
      authors: "Gupta, M.*, Mohanta, R.* et al.",
      title: "Contact Tracing of COVID-19 in Karnataka, India: Evidence for Effective Management",
      venue: "PLOS ONE 17(7):e0270789",
      year: "2022",
      href: "https://doi.org/10.1371/journal.pone.0270789",
    },
    {
      n: 7,
      authors: "Mohanta, R.",
      title: "Deciphering value learning rules in fruit flies using a model-driven approach",
      venue: "IISER Pune Digital Repository",
      year: "2022",
      href: "https://dr.iiserpune.ac.in:8080/xmlui/handle/123456789/7503",
    },
    {
      n: 8,
      authors: "Thimmegowda, G.G. et al. (incl. Mohanta, R.)",
      title: "A field-based quantitative analysis of sublethal effects of air pollution on pollinators",
      venue: "PNAS 117(34)",
      year: "2020",
      href: "https://doi.org/10.1073/pnas.2009074117",
    },
    {
      n: 9,
      authors: "Gupta, M.*, Mohanta, R.* et al.",
      title: "Transmission dynamics of the COVID-19 epidemic in India and modelling optimal lockdown exit strategies",
      venue: "International Journal of Infectious Diseases",
      year: "2020",
      href: "https://doi.org/10.1016/j.ijid.2020.11.206",
    },
    {
      n: 10,
      authors: "Mazumder, A. et al. (incl. Mohanta, R.)",
      title: "Geographical variation in case fatality rate and doubling time during the COVID-19 pandemic",
      venue: "Epidemiology & Infection 148",
      year: "2020",
      href: "https://dx.doi.org/10.1017/S0950268820001685",
    },
  ],

  talksAndPosters: [
    { kind: "Talk",   year: "2024", title: "Decoding Decision-Making in Fruit Flies: Examining Perseverance with a High-Throughput 2AFC Assay and a Computational Model of Mushroom Body Circuitry.", venue: "Cosyne 2024 · Lisbon" , href: "https://www.youtube.com/live/OCr4KV653u8?si=ZxRXkBgX3CsYmANN&t=3300" },
    { kind: "Talk",   year: "2024", title: "Bridging Diverse Perspectives on the Mechanistic Basis of Foraging", venue: "HHMI Janelia Conference · Speaker & Co-organizer" },
    { kind: "Poster", year: "2023", title: "Enumerating and Discovering Highly Discriminative Tasks for Probing Diverse Foraging Strategies", venue: "CCN 2023 · Oxford, UK", href: "https://2023.ccneuro.org/view_paperbe81.html?PaperNum=1217" },
    { kind: "Poster", year: "2022", title: "Deciphering value learning rules underlying fruit-fly behavior", venue: "SfN · San Diego", href: "https://doi.org/10.6084/m9.figshare.21383697" },
    { kind: "Poster", year: "2022", title: "Invariant neural representations of fluctuating odor inputs", venue: "SfN · San Diego", href: "https://doi.org/10.6084/m9.figshare.21383898" },
    { kind: "Poster", year: "2021", title: "Odor coding by attractor switching in the locust antennal lobe", venue: "SfN Global Connectome", href: "https://doi.org/10.6084/m9.figshare.18972815.v2" },
    { kind: "Talk",   year: "2020", title: "Deciphering the Dynamics of the Locust Olfactory System", venue: "Monsoon Brain Meeting", href: "https://www.youtube.com/watch?v=Xjh9elI_VkA" },
    { kind: "Poster", year: "2019", title: "Best Poster — Olfactory learning in closed-loop fly VR", venue: "Asia-Pacific Drosophila Research Conference 5" },
  ],

  teaching: [
    { y: "2025",      t: "Journal Club Mentor · Rockefeller Summer Neuroscience Program." },
    { y: "2024–",     t: "Research mentor to Ruta Lab Research Assistant — FlyCLOPS operation, experimental design, and data analysis." },
    { y: "2024",      t: "Co-organizer · HHMI Janelia Conference on 'Bridging Diverse Perspectives on the Mechanistic Basis of Foraging' — brought together systems neuroscientists, ethologists, ecologists, and theorists; seeded a Trends in Neurosciences review." },
    { y: "2023–",     t: "Community Book Club at Rockefeller — secured microgrant from the Office of University Life; brought Dr. Azra Raza and Dr. Nathan Lents into conversation with students, postdocs, and staff across departments." },
    { y: "2023–",     t: "Annual volunteer · Science Saturday (RockEDU) — interactive tables for the Kronauer ant lab and Ruta optogenetics lab." },
    { y: "2023",      t: "Lead TA · Neuromatch Deep Learning Summer School — supervised 6 TAs, mentored 10 international students across 3 weeks (120 h)." },
    { y: "2023",      t: "Mentor · Tri-Institute Mentorship Initiative — 1-on-1 mentoring for a graduate school applicant." },
    { y: "2021",      t: "Project TA · Neuromatch Deep Learning — mentored 7 international student groups across 3 weeks." },
    { y: "2021",      t: "TA · Neuromatch Computational Neuroscience — daily tutorials for 6 students." },
    { y: "2020",      t: "Workshop instructor · IISER Pune — Python for data analysis and introduction to deep learning." },
  ],

  timeline: [
    { y: "2023–",    t: "PhD · David Rockefeller Graduate Program in Biosciences",       sub: "The Rockefeller University · Ruta & Kronauer Labs" },
    { y: "2022–23",  t: "Research Technician & Offsite Consultant",                       sub: "Turner Lab · HHMI Janelia" },
    { y: "2017–22",  t: "Integrated BS-MS in Biology · CGPA 9.8/10 · with Distinction",  sub: "IISER Pune" },
    { y: "2019",     t: "Janelia Undergraduate Scholar",                                   sub: "Turner Lab · HHMI Janelia" },
    { y: "2018",     t: "Summer intern · chemical ecology",                                sub: "NICE Lab · NCBS Bangalore" },
  ],

  nowArchive: [
    { m: "April 2026",   items: ["Bilateral navigation experiments · FlyCLOPS + MultiBiOS", "HYDRA Suite v1.0 shipping", "Reviewing comparative MB anatomy across hymenoptera"] },
    { m: "January 2026", items: ["Starting bilateral navigation behavioral experiments", "Cosyne 2026 abstract submitted"] },
    { m: "October 2025", items: ["Finishing ant reference brain manuscript revisions", "NS&B course at MBL Woods Hole"] },
    { m: "July 2025",    items: ["HYDRA Suite architecture revamp", "Reading: The Ants (Hölldobler & Wilson)"] },
  ],

  toolDeepDives: {
    "FlyCLOPS": {
      subtitle: "Fly Closed-Loop Optogenetic Pheromone System",
      problem: "Studying bilateral pheromone trail-following requires delivering precise, independently-controllable odor gradients to each antenna — but real odor plumes are turbulent, unrepeatable, and hard to instrument. Chemical delivery also cannot be switched fast enough to run closed-loop experiments.",
      approach: "Replace chemistry with light. Flies expressing channelrhodopsins in specific olfactory receptor neuron classes perceive bilateral optogenetic stimulation as odor, letting us generate virtual pheromone trails with millisecond precision, full bilateral independence, and infinite repeatability — while freely walking on a treadmill.",
      features: [
        "Virtual bilateral odor gradients via targeted optogenetic stimulation",
        "Closed-loop: fly heading drives real-time stimulus updates at >100 Hz",
        "Configurable trail geometries — straight, sinusoidal, branch-point assays",
        "Synchronized behavioral tracking with sub-frame temporal resolution",
        "Hardware-triggered LED control with microsecond jitter",
        "Python experiment scripting with replay and analysis tooling",
      ],
      stack: "Python · NI-DAQmx · Arduino · custom optics",
      status: "in use in the Ruta lab",
    },
    "HYDRA Suite": {
      subtitle: "Holistic YOLO-based Detection, Recognition, and Analysis",
      problem: "Multi-animal behavior studies drown in video. Existing trackers break on occlusion, misassign identities, and offer no integrated workflow from raw footage to analyzable trajectories.",
      approach: "A single toolkit that threads detection, identity assignment, pose labeling, and interactive proofreading. Built around modern detectors with a fast human-in-the-loop correction layer.",
      features: [
        "YOLO-based multi-animal detection tuned for arthropods",
        "Identity persistence across occlusions with re-ID embeddings",
        "Pose labeling tools with active-learning suggestions",
        "Interactive proofreading UI — fix 10 minutes of video in 60 seconds",
        "Batch export to CSV / HDF5 for downstream analysis",
        "Multi-backend GPU support: NVIDIA CUDA, Apple Silicon MPS, AMD ROCm",
      ],
      stack: "Python · PyTorch · YOLOv8 · OpenCV",
      status: "beta · active development",
    },
    "FlyProjection": {
      subtitle: "Closed-loop visual projection system for freely-walking flies",
      problem: "Studying how flies navigate visual scenes requires rendering arbitrary 2D worlds in real time, locked to the animal's position — with latency low enough to genuinely close the loop.",
      approach: "Top-down projector + high-speed IR camera. GPU-accelerated tracking drives a scene renderer; flies experience a 2D world that updates with their movement. Researchers script worlds in Python.",
      features: [
        "GPU-accelerated tracking and rendering pipeline",
        "Basler GigE and CoaXPress camera support",
        "Multi-experiment framework — yin-yang patterns, odor trail approximations, patch foraging",
        "SLEAP-based pose estimation for detailed behavioral analysis",
        "Web application interface for experiment control and monitoring",
        "Built-in calibration routines for arena geometry",
      ],
      stack: "Python · CUDA/cuDNN · FFmpeg · Basler Pylon SDK · SLEAP",
      status: "in use in the Ruta lab",
    },
    "MultiBiOS": {
      subtitle: "Multispecies Bilateral Odor System for comparative olfactometry",
      problem: "Bilateral olfactory navigation experiments require precise, sub-millisecond delivery of olfactory stimuli to left and right antennae independently — in both ants and flies, without timing drift across trials.",
      approach: "A Python-controlled olfactometer using National Instruments DAQ hardware and Teensy 4.1 microcontroller firmware. Declarative YAML experiment scripts, comprehensive trial logging, and built-in visualization.",
      features: [
        "Sub-millisecond hardware-clocked valve timing via Teensy 4.1 firmware",
        "Bilateral valve control for independent left/right odor delivery",
        "Declarative YAML experiment protocols with compile-time safety validation",
        "Complete data provenance — every trial logged with hardware timestamps",
        "Real-time and post-hoc visualization of valve states and odor timing",
        "Reproducible randomization with full seed logging",
      ],
      stack: "Python · C (Teensy firmware) · NI-DAQmx · YAML",
      status: "in use in the Ruta and Kronauer labs",
    },
    "ArthroScape": {
      subtitle: "Arthropod behavioral simulation toolkit",
      problem: "Understanding how individual neural computations — like bilateral comparison or gain modulation — give rise to collective behaviors like trail formation requires tractable, interactive simulation.",
      approach: "An opinionated simulation framework for arthropod agents with tunable sensory and motor modules. Jupyter notebooks serve as both documentation and analysis environment.",
      features: [
        "Bilateral chemosensory navigation models with configurable antenna geometry",
        "Trail formation and aggregation emerging from individual steering rules",
        "Gain modulation effects on collective behavior",
        "Jupyter notebook integration for interactive parameter exploration",
        "Utility scripts for automated builds and reproducible analysis",
      ],
      stack: "Python · NumPy · Jupyter",
      status: "research — in development",
    },
    "FlyManager": {
      subtitle: "Drosophila stock-keeping for working labs",
      problem: "Fly labs juggle hundreds of genotypes, crossing schedules, and vial-aging schedules — most of it in a shared spreadsheet that crashes once a week.",
      approach: "A boring-on-purpose tool. Tracks genotypes, crosses, and vial ages. Reminders for flips. CSV import/export so no lab is locked in.",
      features: [
        "Genotype database with inheritance tracking",
        "Crossing schedule generator",
        "Vial age reminders with flip schedules",
        "QR-label printing for vials",
        "CSV import/export — no lock-in",
      ],
      stack: "Python · SQLite · Flask",
      status: "stable · used daily",
    },
    "MiniVentory": {
      subtitle: "Minimal inventory tracker for small labs",
      problem: "Lab inventory sprawls across sticky notes, shared docs, and one person's memory. Nothing breaks loudly — but ordering duplicates and running out of reagents costs weeks.",
      approach: "A tablet-friendly checkout interface with no login required for users. Administrators manage stock and get low-stock alerts. Easy to adopt, impossible to outgrow badly.",
      features: [
        "Simple no-login consumables checkout for lab members",
        "Admin dashboard secured by PIN with analytics",
        "Low-stock email alerts with configurable thresholds",
        "Configurable summary reports (daily/weekly)",
        "Per-item automatic replenishment schedules",
        "CSV export and audit logging",
      ],
      stack: "Python · Flask · MongoDB · Docker",
      status: "stable",
    },
  },

  pillarDeepDives: {
    navigation: {
      tagline: "How does sensory anatomy shape the neural implementation of a conserved computation?",
      opening: "Ants smell the world through 120,000 olfactory receptor neurons; flies use 1,200. Both navigate using pheromone trails. My PhD asks why the implementation is so different — and what that difference reveals about the relationship between sensory organs, neural circuits, and behavior.",
      questions: [
        "What bilateral comparison algorithm underlies pheromone trail-following — and is it the same in ants and flies?",
        "How do differences in antennal anatomy and spacing constrain the circuits available to each species?",
        "Can we build a comparative atlas of olfactory circuits that is actually useful to a field biologist?",
      ],
      projects: [
        { y: "2023–", t: "Bilateral olfactory navigation in Ooceraea biroi and Drosophila", lab: "Ruta + Kronauer Labs · Rockefeller", detail: "Using FlyCLOPS (virtual optogenetic odor trails in flies) and MultiBiOS (real bilateral odor delivery in ants and flies) to compare navigation algorithms across species with a 100× difference in olfactory scale. Integrating connectomics, optogenetics, 2p imaging, and computational modeling." },
        { y: "2026", t: "Standard reference brain for the clonal raider ant", lab: "Kronauer Lab · Rockefeller", detail: "Built the first neuroanatomical reference brain for O. biroi — published in Current Biology 2026 — now used as a shared coordinate system for ant neuroscience by the wider community." },
        { y: "2019–21", t: "Locust antennal-lobe dynamics under fluctuating odor", lab: "Assisi Lab · IISER Pune", detail: "Showed that the locust AL produces invariant odor representations even when inputs are intermittent or temporally overlapping." },
      ],
    },
    learning: {
      tagline: "How do nervous systems assign value to experience and use it to navigate the world?",
      opening: "Flies, ants, and mice all learn from reward and punishment, but the circuits that implement this look wildly different on paper. I use behavior, imaging, and models to ask what computational rules they share — and what we can learn from the differences.",
      questions: [
        "Can we manipulate fly choice by engineering the reward landscape — and does that reveal the underlying learning rule?",
        "When animals learn in naturalistic foraging environments, which learning-rule signatures appear?",
        "What makes some tasks maximally informative about an animal's decision-making strategy?",
      ],
      projects: [
        { y: "2022–23", t: "Choice engineering in fruit flies", lab: "Turner Lab · HHMI Janelia · DeepMind collaboration", detail: "Model-driven manipulation of fly olfactory decisions. Behavioral data contributed to a Google DeepMind LLM-based symbolic model discovery paper at ICML 2025." },
        { y: "2023", t: "Maximally discriminative tasks for foraging strategy probing", lab: "Hermundstad Lab · HHMI Janelia", detail: "Developed principled methods for enumerating tasks that maximally distinguish between foraging strategies — presented at CCN 2023 and Cosyne 2024." },
        { y: "2019", t: "Olfactory learning in fly VR", lab: "Turner Lab · HHMI Janelia", detail: "Closed-loop fly-on-ball arena to probe how olfactory learning shapes exploratory walking behavior, with focus on exploration-exploitation tradeoffs." },
      ],
    },
    tools: {
      tagline: "Tools that make comparative neuroethology tractable.",
      opening: "Comparative work needs comparable data. That means shared rigs, shared analysis pipelines, and shared reference frames. Most of my tools exist because I needed them for my own science — and they keep getting useful to other people.",
      questions: [
        "What's the smallest, most re-usable unit of a bilateral behavioral rig?",
        "How do we make identity-preserving multi-animal tracking work without a GPU farm?",
        "What does a good comparative-atlas workflow look like, end to end?",
      ],
      projects: [
        { y: "2025–", t: "HYDRA Suite", lab: "Rockefeller", detail: "Multi-animal tracking with identity persistence, pose labeling, and interactive proofreading in one workflow. Built to handle the scale of ant colony videos." },
        { y: "2024–", t: "FlyProjection · MultiBiOS", lab: "Ruta + Kronauer Labs · Rockefeller", detail: "Closed-loop visual arena for free-walking flies and precision bilateral olfactometer for comparative pheromone navigation experiments." },
        { y: "2019", t: "Parallel TensorFlow sim framework", lab: "Assisi Lab · IISER Pune", detail: "A beginner-friendly toolkit for GPU-accelerated biological neural-network simulation; published in NBDT 2022." },
      ],
    },
  },
};
